name = "pingflare"
main = "src/index.ts"
compatibility_date = "2026-07-27"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[vars]
PINGFLARE_INSTANCE_ID = "pingflare"
API_ANALYTICS_SAMPLE_RATE = "0.05"

[secrets]
required = ["ADMIN_USER", "ADMIN_PASS", "JWT_SECRET", "ENCRYPTION_KEY"]

[assets]
directory = "./frontend/build"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/h/*"]

[[d1_databases]]
binding = "DB"
database_name = "pingflare"
database_id = "57c162e7-edab-4cb0-9420-14cc6d630015"
migrations_dir = "drizzle"

[[analytics_engine_datasets]]
binding = "CHECK_ANALYTICS"
dataset = "pingflare_check_events_v1"

[[analytics_engine_datasets]]
binding = "API_ANALYTICS"
dataset = "pingflare_api_events_v1"

[[ratelimits]]
name = "LOGIN_RATE_LIMITER"
namespace_id = "104142"

[ratelimits.simple]
limit = 5
period = 60

[triggers]
crons = [
  "* * * * *"
]

[observability]
enabled = true
head_sampling_rate = 0.1

[observability.logs]
enabled = true
head_sampling_rate = 0.1
persist = false
invocation_logs = false
